os: linux
dist: focal
services:
  - docker
language: node_js
node_js:
  - 17

stages:
  - name: "publish"
    if: type = push

jobs:
  include:
    - stage: "publish"
      name: "publish" 
      if: branch = master
      env:
        - IMAGE=pivpn/pivpn.io
      install:
        - npm install @semantic-release/github -D
        - npm install @semantic-release/changelog -D
        - npm install @semantic-release-plus/docker -D
      before_script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      script:
        - docker build -t $IMAGE .
        - npx semantic-release

