services:
  - docker

stages:
  - test
  - name: "Build&Publish"
    if: type = push

branches:
  only:
    - test
    - master

jobs:
  include:
    - stage: "test"
      name: "Test PR"
      if: type = pull_request
      before_script:
        - docker login -u $dockeruser -p $dockerpass
      script:
        - docker build -t pivpn/pivpn.io:PR-$TRAVIS_BRANCH-$TRAVIS_COMMIT .
        - docker push pivpn/pivpn.io:PR-$TRAVIS_BRANCH-$TRAVIS_COMMIT

    - stage: "Build&Publish"
      name: "Build&Deploy" 
      if: type = push
      before_script:
        - docker login -u $dockeruser -p $dockerpass
      script:
        - docker build -t pivpn/pivpn.io:$tag .
        - docker push pivpn/pivpn.io:$tag
