services:
  - docker

stages:
  - name: "Build&Publish"

jobs:
  include:
    - stage: "Build&Publish"
      name: "Build&Deploy"
      if: type = push
      before_script:
        - echo $dockerpass | docker login -u $dockeruser  --password-stdin
      script:
        - docker build -t $webrepo:$tag .
        - docker push $webrepo:$tag
